SGCM.Web/Controllers/LoginController.cs
using SGCM.Core.Services.Repository;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SGCM.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserRepository _userRepository;

        public LoginController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> ValidateUser(string email, string password)
        {
            var user = await _userRepository.GetUser(email, password);

            if (user != null)
            {
                Session["user"] = user;
                Session["userType"] = user.UserType;

                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json("Email/Contraseña incorrecta.", JsonRequestBehavior.AllowGet);
        }

        public ActionResult LogOut()
        {
            Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

SGCM.Web/Controllers/RegistrationController.cs
using SGCM.Core.Models;
using SGCM.Core.Services;
using SGCM.Core.Services.Repository;
using SGCM.Web.Controllers.Base;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SGCM.Web.Controllers
{
    public class RegistrationController : BaseController
    {
        private readonly IUserRepository _userRepository;
        private readonly IMailManager _mailManager;

        public RegistrationController(IUserRepository userRepository, IMailManager mailManager)
        {
            _userRepository = userRepository;
            _mailManager = mailManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> RegisterUser(PatientRegistration patient)
        {
            try
            {
                if (await _userRepository.UserExist(patient.Email))
                {
                    throw new Exception("Este correo ya está registrado.");
                }

                await _userRepository.RegisterUser(patient);

                string bodyHtml = RenderViewToString("WelcomeEmail", patient.Email);

                await _mailManager.SendEmail(patient.Email, "SGCM - Bienvenida", bodyHtml);

                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SGCM.Web/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br /><br /><br />
<section class="team-area section-gap">
    <div class="container">
        <div class="single-footer-widget newsletter">
            <div class="row">
                <div class="col-md-6">
                    <h2>Iniciar Sesion</h2>
                </div>

            </div>
            <div id="mc_embed_signup">
                <form target="_blank" action="" method="get" class="form-inline">

                    <div class="form-group row" style="width: 100%">
                        <div class="col-lg-8 col-md-10">
                            <label style="font:bold">Correo Electronico</label>
                            <input id="email" placeholder="Dirreción de correo electronico" required="" type="email" style="border-style:solid; border-color:black; border-width:thin">
                        </div>
                        <div class="col-lg-8 col-md-10">
                            <label style="font:bold">Contraseña</label>
                            <input id="pass" placeholder="Contraseña" onfocus="this.placeholder = ''" required="" type="password" style="border-style:solid; border-color:black; border-width:thin">
                        </div>

                        <div> </div>
                        <div> </div>
                    </div>
                    <div class="col-lg-4 col-md-12">
                        <br>
                        <button id="validate" class="btn btn-success circle">Iniciar <span class="lnr lnr-arrow-right"></span></button>
                    </div>
                    
                    <div class="col-lg-4 col-md-12">
                        <br>
                        <a id="Registrar" href="@Url.Action("Index","Registration")" class="btn btn-info circle ">Registro <span class="lnr lnr-arrow-right"></span></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section scripts {
    <script>
        $("#header").addClass("header-scrolled");

        $("#validate").on("click", function () {
            var email = $("#email").val();
            var password = $("#pass").val();

            var buttoHtml = $("#validate").html();

            $("#validate").html("<i class='fa fa-refresh fa-spin'></i>");

            $.ajax({
				url: "@Url.Action("ValidateUser")",
                type: "POST",
                data: { email: email, password: password},
                success: function (data) {
                    $("#validate").html(buttoHtml);
                    if (data.toString() == "true") {
                        location.href = "@Url.Action("Index", "Home")";
                    }
                    else {
                        $("#validate").html(buttoHtml);
                        alert(data);
                    }
				},
				error: function (data) {

				}
			});
        });
    </script>
}