SGCM.Web/Controllers/AppointmentController.cs
using SGCM.Core.Models;
using SGCM.Core.Services;
using SGCM.Core.Services.Repository;
using SGCM.Web.Controllers.Base;
using SGCM.Web.Filters;
using SGCM.Web.Models;
using SGCM.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SGCM.Web.Controllers
{
    public class AppointmentController : BaseController
    {
        private readonly IServiceUnitRepository _serviceUnitRepository;
        private readonly IScheduleRepository _scheduleRepository;
        private readonly IScheduleDayRepository _scheduleDayRepository;
        private readonly IMailManager _mailManager;
        private readonly IServiceRepository _serviceRepository;

        public AppointmentController(IServiceUnitRepository serviceUnitRepository,
            IScheduleRepository scheduleRepository,
            IScheduleDayRepository scheduleDayRepository,
            IServiceRepository serviceRepository,
            IMailManager mailManager)
        {
            _serviceUnitRepository = serviceUnitRepository;
            _scheduleRepository = scheduleRepository;
            _scheduleDayRepository = scheduleDayRepository;
            _mailManager = mailManager;
            _serviceRepository = serviceRepository;
        }

        [UserLogged]
        public ActionResult Index(bool pendings = true)
        {
            var user = Session["user"] as User;
            ViewBag.Pendings = pendings;

            IEnumerable<ScheduleDay> appointments;

            if (pendings)
                appointments = _scheduleDayRepository.GetPendingPatientAppointments(user.UserId).ToArray();
            else
                appointments = _scheduleDayRepository.GetAllPatientAppointments(user.UserId).ToArray();

            return View(appointments.OrderBy(v=>v.Date));
        }

        [UserLogged]
        public ActionResult Doctor(bool pendings = true)
        {
            var user = Session["user"] as User;
            ViewBag.Pendings = pendings;

            IEnumerable<ScheduleDay> appointments;

            if (pendings)
                appointments = _scheduleDayRepository.GetPendingDoctorAppointments(user.UserId);
            else
                appointments = _scheduleDayRepository.GetAllDoctorAppointments(user.UserId);

            return View(appointments);
        }

        [UserLogged]
        public ActionResult Create()
        {
            var model = new AppointmentCreateVM
            {
                Months = Enum.GetValues(typeof(Months)).Cast<Months>(),
                ServiceUnits = _serviceUnitRepository.GetAll()
            };

            return View(model);
        }

        public async Task<ActionResult> Confirmation(int userId, CreateAppointmentVM appointment)
        {
            try
            {
                var appointmentDate = new DateTime(appointment.Year, appointment.Month, appointment.Day);

                await _scheduleDayRepository.ConfirmAppointment(userId, appointment.ServiceId, appointment.UnitId, appointmentDate);

                ViewBag.Message = "Cita Confirmada";
            }
            catch (Exception e)
            {
                ViewBag.Message = $"Error: {e.Message}";
            }

            return View();

        }

        [HttpPost]
        public PartialViewResult AppointmentDetail(AppointmentDetailVM appointmentDetail)
        {
            var date = new DateTime(appointmentDetail.Year, appointmentDetail.Month, appointmentDetail.Day);

            var appointments = _scheduleDayRepository.GetAppointments(appointmentDetail.UnitId, date);

            var model = new AppointmentVM
            {
                AppointmentDetail = appointmentDetail,
                Date = date,
                Services = _serviceRepository.GetAll(),
                Appointments = appointments
            };

            return PartialView(model);
        }

        public PartialViewResult BuildSchedule(int unitId, int year, int month)
        {
            var result = _scheduleRepository.Get(year, month, unitId);
            return PartialView(result);
        }

        [HttpPost]
        public async Task<JsonResult> CreateAppointment(CreateAppointmentVM appointment)
        {
            try
            {
                var appointmentDate = new DateTime(appointment.Year, appointment.Month, appointment.Day);

                var user = Session["user"] as User;

                await _scheduleDayRepository.CreateAppointment(user.UserId, appointment.ServiceId, appointment.UnitId, appointmentDate);

                var scheduleDayCreated = _scheduleDayRepository.GetScheduleDay(appointment.UnitId, user.UserId, appointmentDate);

                string emailHtml = RenderViewToString("SendConfirmationEmail",
                    new SendConfirmationEmailVM
                    {
                        User = user,
                        AppointmentDate = appointmentDate,
                        ScheduleDay = scheduleDayCreated,
                        ServiceId = appointment.ServiceId,
                        UnitId = appointment.UnitId
                    });

                await _mailManager.SendEmail(user.Email, "SGCM - Confirmación de Cita", emailHtml);

                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SGCM.Web/Controllers/LoginController.cs
using SGCM.Core.Services.Repository;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SGCM.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserRepository _userRepository;

        public LoginController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> ValidateUser(string email, string password)
        {
            var user = await _userRepository.GetUser(email, password);

            if (user != null)
            {
                Session["user"] = user;
                Session["userType"] = user.UserType;

                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json("Email/Contraseña incorrecta.", JsonRequestBehavior.AllowGet);
        }

        public ActionResult LogOut()
        {
            Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

SGCM.Web/Views/Shared/_Layout.cshtml
@{ 
    var user = Session["user"] as SGCM.Core.Models.User;
}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    @*<link rel="shortcut icon" href="img/fav.png">*@
    <!-- Author Meta -->
    <meta name="author" content="Grupo 3">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>@ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/jquery-ui.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/jquery-ui.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <header id="header">
        @RenderPage("_MenuBar.cshtml")
    </header><!-- #header -->
    @RenderBody()
    <!-- start footer Area -->
    <footer class="footer-area section-gap" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-6">
                    <div class="single-footer-widget">
                        <h6>Top Servicios</h6>
                        <ul class="footer-nav">
                            <li><a href="#service"></a></li>
                            <li><a href="#service">Seguimiento</a></li>
                            <li><a href="#service">Analisis</a></li>
                            <li><a href="#service">Marketing Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4  col-md-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">Contact Us</h6>
                        <p>
                            56/8, Santa bullevard, Rocky beach, San fransisco, Los angeles, USA
                        </p>
                        <h3>012-6532-568-9746</h3>
                        <h3>012-6532-568-97468</h3>
                    </div>
                </div>
                <div class="col-lg-6  col-md-12">
                    <div class="single-footer-widget newsletter">
                        @if (user != null)
                        {
                            <h6>Usuario</h6>
                            <Label>@user</Label>
                        }
                    </div>
                        </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between">
                <p class="col-lg-8 col-sm-12 footer-text m-0">

                </p>
                @*<div class="col-lg-4 col-sm-12 footer-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>*@
            </div>
        </div>
    </footer>
    <!-- End footer Area -->
    <script src="~/Scripts/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/vendor/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/easing.min.js"></script>
    <script src="~/Scripts/hoverIntent.js"></script>
    <script src="~/Scripts/superfish.min.js"></script>
    <script src="~/Scripts/jquery.ajaxchimp.min.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/jquery.tabs.min.js"></script>
    <script src="~/Scripts/jquery.nice-select.min.js"></script>
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <script src="~/Scripts/mail-script.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/customScripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

SGCM.Web/Views/Shared/_MenuBar.cshtml
@using SGCM.Core.Enums;
@{ 
    var usserLogged = Session["user"] != null;

    var userType = Session["userType"] as UserTypes?;
}
<div class="container main-menu">
    <div class="row align-items-center justify-content-between d-flex">
        <div id="logo">
            <a href="@Url.Action("Index", "Home")"><h3 style="color: white; text-decoration: none;">SGCM</h3></a>
        </div>
        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li><a href="@Url.Action("Index", "Home")#home">Inicio</a></li>
                <li><a href="@Url.Action("Index", "Home")#service">Servicios</a></li>
                <li><a href="@Url.Action("Index", "Home")#footer">Contacto</a></li>

                @if (!usserLogged)
                {
                    <li><a href="@Url.Action("Index", "Login")">Login</a></li>
                }
                else
                {
                    if (userType.Value == UserTypes.Patient)
                    {
                        <li><a href="@Url.Action("Index", "Appointment")">Citas</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Doctor", "Appointment")">Citas</a></li>
                    }
                    <li><a href="@Url.Action("LogOut", "Login")">Salir</a></li>
                }


                @*<li class="menu-has-children">
            <a href="">Blog</a>
            <ul>
                <li><a href="blog-home.html">Blog Home</a></li>
                <li><a href="blog-single.html">Blog Single</a></li>
            </ul>
        </li>*@

            </ul>
        </nav><!-- #nav-menu-container -->
    </div>
</div>